const mongoose = require('mongoose')
mongoose.Promise=global.Promise;
const db ={};
db.mongoose=mongoose;
db.contact=require('./contact')
db.competence=require('./competence')
db.centreInteret=require('./centreInteret')
db.langue=require('./langue')
db.experience=require('./experience')
db.formation=require('./formation')
db.entete=require('./entete')
db.cv=require('./cv')
module.exports=db;